"""
flow_store.py — Supabase DB writer for live options flow.

Subscribes to the async event bus and persists every classified
OptionsFlowEvent to `flow_events` and every signal episode to
`flow_episodes`.

Usage — call once at startup from main.py lifespan:

    from services.flow_store import start_flow_writer
    asyncio.create_task(start_flow_writer())

Tables written:
  - flow_events   : one row per classified tick (batched every 5s)
  - flow_episodes : one row per repetition episode that crossed threshold
                    (written immediately on every qualifying signal)

NOTE: Neither table receives an `id` field — Postgres generates it
      (uuid default for flow_events, bigserial for flow_episodes).

This module is the ONLY place that writes options flow data to the DB.
The async_bus is purely in-memory fan-out for WebSocket delivery.

IMPORTANT — Key selection:
  Only SUPABASE_SERVICE_ROLE_KEY is used here. The service role key
  bypasses Row Level Security (RLS) which is required for server-side
  inserts. The anon/public key (SUPABASE_KEY) respects RLS and will
  cause every insert to fail with a 42501 policy violation. Never use
  the anon key for backend DB writes.

Fix (C-010):
  - Env var corrected: SUPABASE_SERVICE_KEY → SUPABASE_SERVICE_ROLE_KEY
  - persist_flow_event() now writes ALL flow_events columns:
    fill_price, bid, ask, size, dte, bid_ask_class, is_aggressive,
    exchange_count, fill_count, open_interest, iv, underlying_price.
  - expiry sent as None (not "") when empty so Postgres DATE/TEXT column
    does not receive an empty string that triggers a cast error.

Fix (C-011):
  - strike=0 sent as 0.0 (not None) — parser now skips zero-strike trades
    so any trade reaching here has a valid strike.
  - _bus_signal_listener now handles both 'signal' and 'composite_signal'
    event types — previously composite_signal events were silently dropped.
  - persist_flow_event logs a warning when strike or expiry is missing
    so parsing quality can be monitored in Railway logs.

Architecture change (Layer 1+2):
  - occ_symbol field now written to flow_events.occ_symbol column.
    This stores the raw OCC contract string (e.g. "AAPL  260117C00180000")
    for every persisted trade, enabling contract-level querying and auditing.
"""
import asyncio
import logging
import os
from datetime import datetime, timezone
from typing import Optional

import httpx

log = logging.getLogger("flow_store")

_SUPABASE_URL: Optional[str] = os.environ.get("SUPABASE_URL")

# IMPORTANT: Use the service role key ONLY — it bypasses RLS.
# Never fall back to the anon key (SUPABASE_KEY) here; the anon key
# respects RLS and will produce 401/42501 errors on every insert.
# Env var name: SUPABASE_SERVICE_ROLE_KEY  (Railway config)
_SUPABASE_KEY: Optional[str] = (
    os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    or os.environ.get("SUPABASE_SERVICE_KEY")  # legacy fallback
)

# Batch insert flow_events every N seconds to avoid per-tick DB hammering
_FLUSH_INTERVAL = 5  # seconds
_flow_event_buffer: list[dict] = []


def _headers() -> dict:
    return {
        "apikey":        _SUPABASE_KEY,
        "Authorization": f"Bearer {_SUPABASE_KEY}",
        "Content-Type":  "application/json",
        "Prefer":        "return=minimal",
    }


async def _insert_rows(table: str, rows: list[dict]) -> bool:
    """POST rows to a Supabase REST table. Returns True on success."""
    if not rows or not _SUPABASE_URL or not _SUPABASE_KEY:
        return False
    url = f"{_SUPABASE_URL}/rest/v1/{table}"
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(url, headers=_headers(), json=rows)
        if resp.status_code in (200, 201):
            return True
        log.error(f"[flow_store] insert into {table} failed: {resp.status_code} — {resp.text[:300]}")
        return False
    except Exception as e:
        log.error(f"[flow_store] insert into {table} exception: {e}")
        return False


async def _flush_flow_events():
    """Periodic flusher — drains buffer into flow_events table."""
    global _flow_event_buffer
    while True:
        await asyncio.sleep(_FLUSH_INTERVAL)
        if not _flow_event_buffer:
            continue
        batch = _flow_event_buffer.copy()
        _flow_event_buffer.clear()
        ok = await _insert_rows("flow_events", batch)
        if ok:
            log.info(f"[flow_store] flushed {len(batch)} flow_events to DB")
        else:
            log.warning(f"[flow_store] failed to flush {len(batch)} flow_events — data lost")


async def persist_flow_event(ev_dict: dict):
    """
    Buffer a raw classified flow tick for batch insert into flow_events.

    NOTE: No `id` field is sent — flow_events.id is a uuid generated by Postgres.

    ev_dict is built from a full OptionsFlowEvent in tradier_stream._process_trade().
    All columns of the flow_events table are populated here, including occ_symbol.

    expiry is coerced to None when empty string so Postgres does not
    receive '' for a TEXT/DATE column.

    strike
