"""
flow_store.py — Supabase DB writer for live options flow.

Subscribes to the async event bus and persists every classified
OptionsFlowEvent to `flow_events` and every signal episode to
`flow_episodes`.

Usage — call once at startup from main.py lifespan:

    from services.flow_store import start_flow_writer
    asyncio.create_task(start_flow_writer())

Tables written:
  - flow_events   : one row per classified tick (batched every 5s)
  - flow_episodes : one row per repetition episode that crossed threshold
                    (written immediately on every qualifying signal)

NOTE: Neither table receives an `id` field — Postgres generates it
      (uuid default for flow_events, bigserial for flow_episodes).

This module is the ONLY place that writes options flow data to the DB.
The async_bus is purely in-memory fan-out for WebSocket delivery.

IMPORTANT — Key selection:
  Only SUPABASE_SERVICE_ROLE_KEY is used here. The service role key
  bypasses Row Level Security (RLS) which is required for server-side
  inserts. The anon/public key (SUPABASE_KEY) respects RLS and will
  cause every insert to fail with a 42501 policy violation. Never use
  the anon key for backend DB writes.
"""
import asyncio
import logging
import os
from datetime import datetime, timezone
from typing import Optional

import httpx

log = logging.getLogger("flow_store")

_SUPABASE_URL: Optional[str] = os.environ.get("SUPABASE_URL")

# IMPORTANT: Use the service role key ONLY — it bypasses RLS.
# Never fall back to the anon key (SUPABASE_KEY) here; the anon key
# respects RLS and will produce 401/42501 errors on every insert.
_SUPABASE_KEY: Optional[str] = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

# Batch insert flow_events every N seconds to avoid per-tick DB hammering
_FLUSH_INTERVAL = 5  # seconds
_flow_event_buffer: list[dict] = []


def _headers() -> dict:
    return {
        "apikey":        _SUPABASE_KEY,
        "Authorization": f"Bearer {_SUPABASE_KEY}",
        "Content-Type":  "application/json",
        "Prefer":        "return=minimal",
    }


async def _insert_rows(table: str, rows: list[dict]) -> bool:
    """POST rows to a Supabase REST table. Returns True on success."""
    if not rows or not _SUPABASE_URL or not _SUPABASE_KEY:
        return False
    url = f"{_SUPABASE_URL}/rest/v1/{table}"
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(url, headers=_headers(), json=rows)
        if resp.status_code in (200, 201):
            return True
        log.error(f"[flow_store] insert into {table} failed: {resp.status_code} — {resp.text[:300]}")
        return False
    except Exception as e:
        log.error(f"[flow_store] insert into {table} exception: {e}")
        return False


async def _flush_flow_events():
    """Periodic flusher — drains buffer into flow_events table."""
    global _flow_event_buffer
    while True:
        await asyncio.sleep(_FLUSH_INTERVAL)
        if not _flow_event_buffer:
            continue
        batch = _flow_event_buffer.copy()
        _flow_event_buffer.clear()
        ok = await _insert_rows("flow_events", batch)
        if ok:
            log.info(f"[flow_store] flushed {len(batch)} flow_events to DB")
        else:
            log.warning(f"[flow_store] failed to flush {len(batch)} flow_events — data lost")


async def persist_flow_event(ev_dict: dict):
    """
    Buffer a raw classified flow tick for batch insert into flow_events.

    NOTE: No `id` field is sent — flow_events.id is a uuid generated by Postgres.

    Expected ev_dict keys (from parse_tradier_trade output):
      ticker, contract_type, strike, expiry, premium,
      trade_type, sentiment, influence_tier, conviction_score,
      is_golden_sweep
    """
    row = {
        "ticker":           ev_dict.get("ticker"),
        "contract_type":    ev_dict.get("contract_type"),
        "strike":           ev_dict.get("strike"),
        "expiry":           ev_dict.get("expiry"),
        "premium":          ev_dict.get("premium"),
        "trade_type":       ev_dict.get("trade_type", "UNKNOWN"),
        "sentiment":        ev_dict.get("sentiment", "UNKNOWN"),
        "influence_tier":   ev_dict.get("influence_tier", "UNKNOWN"),
        "conviction_score": ev_dict.get("conviction_score", 0.0),
        "is_golden_sweep":  ev_dict.get("is_golden_sweep", False),
        # created_at: let Postgres default (now())
    }
    _flow_event_buffer.append(row)


async def persist_flow_episode(signal_data: dict):
    """
    Immediately insert a flow signal episode into flow_episodes.

    NOTE: No `id` field is sent — flow_episodes.id is a bigserial generated by Postgres.

    signal_data is the 'data' dict from the bus signal payload:
      ticker, direction, contract_type, strike, expiry,
      total_premium, trade_count, alert_level, is_accelerating,
      seed_episode, timestamp
    """
    row = {
        "ticker":          signal_data.get("ticker"),
        "direction":       signal_data.get("direction"),
        "contract_type":   signal_data.get("contract_type"),
        "strike":          signal_data.get("strike"),
        "expiry":          signal_data.get("expiry"),
        "total_premium":   signal_data.get("total_premium"),
        "trade_count":     signal_data.get("trade_count"),
        "alert_level":     signal_data.get("alert_level"),
        "is_accelerating": signal_data.get("is_accelerating", False),
        "seed_episode":    signal_data.get("seed_episode"),
        "signal_ts":       signal_data.get("timestamp"),
        # created_at: let Postgres default (now())
    }
    ok = await _insert_rows("flow_episodes", [row])
    if ok:
        # f-string — evaluates immediately, never deferred by logging formatter
        log.info(
            f"[flow_store] flow_episode saved: {row['ticker']} {row['contract_type']} "
            f"alert={row['alert_level']} prem=${(row['total_premium'] or 0):,.0f}"
        )


async def _bus_signal_listener():
    """
    Subscribe to the async bus on the 'db_writer' channel.
    On every signal published by tradier_stream, persist the flow episode.
    """
    from core.async_bus import bus
    q = bus.subscribe("db_writer")
    log.info("[flow_store] DB writer subscribed to bus — flow_episodes will be persisted")
    try:
        while True:
            signal = await q.get()
            if isinstance(signal, dict) and signal.get("type") == "signal":
                await persist_flow_episode(signal.get("data", {}))
    except asyncio.CancelledError:
        bus.unsubscribe("db_writer", q)
        log.info("[flow_store] DB writer unsubscribed from bus")
        raise


async def start_flow_writer():
    """
    Entry point — start both the bus listener and the periodic flusher.
    Call this once from main.py lifespan as an asyncio task.

        stream_task   = asyncio.create_task(stream_options_flow(symbols))
        db_write_task = asyncio.create_task(start_flow_writer())   # <-- add this
    """
    if not _SUPABASE_URL or not _SUPABASE_KEY:
        log.warning(
            "[flow_store] SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not set — "
            "flow_events and flow_episodes will NOT be persisted to DB. "
            "Ensure SUPABASE_SERVICE_ROLE_KEY (not the anon key) is set in Railway env vars."
        )
        return

    log.info(f"[flow_store] Starting flow DB writer (flush_interval={_FLUSH_INTERVAL}s)")
    await asyncio.gather(
        _bus_signal_listener(),
        _flush_flow_events(),
    )
