"""
config.py — Application settings loaded from environment variables.

All secrets are read from the environment; no defaults are hardcoded
except for non-sensitive operational parameters.
"""
from __future__ import annotations

import os
from functools import lru_cache
from typing import Optional

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    # ── Auth ──────────────────────────────────────────────────────────────────
    SECRET_KEY: str = os.environ.get("SECRET_KEY", "change-me-in-production")
    ALGORITHM:  str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 1440  # 24 h

    # ── Supabase ──────────────────────────────────────────────────────────────
    SUPABASE_URL:              str = os.environ.get("SUPABASE_URL",              "https://placeholder.supabase.co")
    SUPABASE_ANON_KEY:         str = os.environ.get("SUPABASE_ANON_KEY",         "")
    SUPABASE_SERVICE_ROLE_KEY: str = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")
    SUPABASE_SERVICE_KEY:      str = os.environ.get("SUPABASE_SERVICE_KEY",      "")  # legacy alias

    # ── Tradier ───────────────────────────────────────────────────────────────
    TRADIER_API_KEY:      str = os.environ.get("TRADIER_API_KEY",      "")
    TRADIER_STREAM_TOKEN: str = os.environ.get("TRADIER_STREAM_TOKEN", "")
    TRADIER_ACCOUNT_ID:   str = os.environ.get("TRADIER_ACCOUNT_ID",   "")
    TRADIER_BASE_URL: str = os.environ.get(
        "TRADIER_BASE_URL", "https://api.tradier.com"
    )

    # ── AI / LLM ──────────────────────────────────────────────────────────────
    GROQ_API_KEY:   Optional[str] = os.environ.get("GROQ_API_KEY", None) or None
    SWARM_N_AGENTS: int           = int(os.environ.get("SWARM_N_AGENTS", "6"))

    # ── Universe / stream eligibility ─────────────────────────────────────────
    UNIVERSE_MIN_PRICE: float = float(os.environ.get("UNIVERSE_MIN_PRICE", "1.0"))
    UNIVERSE_MIN_VOLUME: int = int(os.environ.get("UNIVERSE_MIN_VOLUME", "100000"))
    UNIVERSE_QUOTES_BATCH_SIZE: int = int(os.environ.get("UNIVERSE_QUOTES_BATCH_SIZE", "200"))
    UNIVERSE_QUOTES_CONCURRENCY: int = int(os.environ.get("UNIVERSE_QUOTES_CONCURRENCY", "28"))

    # ── App ───────────────────────────────────────────────────────────────────
    APP_ENV:   str = os.environ.get("APP_ENV",   "production")
    LOG_LEVEL: str = os.environ.get("LOG_LEVEL", "INFO")

    # ── CORS ──────────────────────────────────────────────────────────────────
    # Production domains  : cipher-flame.vercel.app
    #                       cipher-bhaveshhpatels-projects.vercel.app
    #                       cipher-git-main-bhaveshhpatels-projects.vercel.app
    # Apex preview domain : cipher-git-apex-engine-bhaveshhpatels-projects.vercel.app
    #                       (auto-generated by Vercel for apex/engine branch)
    # Override at runtime via CORS_ALLOWED_ORIGINS env var (comma-separated).
    CORS_ALLOWED_ORIGINS: str = os.environ.get(
        "CORS_ALLOWED_ORIGINS",
        ",".join([
            "https://cipher-flame.vercel.app",
            "https://cipher-bhaveshhpatels-projects.vercel.app",
            "https://cipher-git-main-bhaveshhpatels-projects.vercel.app",
            "https://cipher-git-apex-engine-bhaveshhpatels-projects.vercel.app",
            "http://localhost:3000",
        ]),
    )

    # ── Apex signal engine ────────────────────────────────────────────────────
    # Set APEX_MODE=true on the cipher-backend-apex Railway service.
    # The main cipher-backend service should always have APEX_MODE=false.
    APEX_MODE:                  bool  = os.environ.get("APEX_MODE", "false").lower() == "true"
    APEX_MAX_SPREAD_PCT:        float = float(os.environ.get("APEX_MAX_SPREAD_PCT",        "0.15"))
    APEX_MIN_TRADE_PREMIUM:     float = float(os.environ.get("APEX_MIN_TRADE_PREMIUM",     "5000"))
    APEX_AGGRESSION_HARD_REJECT: bool = os.environ.get("APEX_AGGRESSION_HARD_REJECT", "false").lower() == "true"

    # ── Symbol registry / OI build ────────────────────────────────────────────
    REGISTRY_T1_DTE:                  int   = 90
    REGISTRY_T2_DTE:                  int   = 60
    REGISTRY_T3_DTE:                  int   = 30
    REGISTRY_ATM_RANGE_PCT:           float = 0.15
    REGISTRY_REFRESH_MINS:            int   = 30
    REGISTRY_MIN_OI:                  int   = 0
    REGISTRY_EXPIRY_DAY_REFRESH_MINS: int   = 15

    # ── Ingestion kill-switch ─────────────────────────────────────────────────
    # Set INGESTION_ENABLED=false in preview/staging environments to prevent
    # duplicate writes to shared production Supabase tables.
    #
    # TODO(parallel-schema): Remove this flag once Option A/B parallel schema
    # isolation is in place — writes should be scoped to preview schema instead.
    INGESTION_ENABLED: bool = os.environ.get("INGESTION_ENABLED", "true").lower() not in ("false", "0", "no")

    # ── Computed aliases (plain properties, visible to hasattr) ───────────────

    @property
    def JWT_SECRET(self) -> str:  # noqa: N802
        """Alias for SECRET_KEY — tests assert hasattr(settings, 'JWT_SECRET')."""
        return self.SECRET_KEY

    @property
    def SUPABASE_KEY(self) -> Optional[str]:  # noqa: N802
        """Alias: returns first non-empty Supabase key available."""
        return (
            self.SUPABASE_SERVICE_ROLE_KEY
            or self.SUPABASE_SERVICE_KEY
            or self.SUPABASE_ANON_KEY
            or None
        ) or None

    # ── Origins helper used by main.py ────────────────────────────────────────
    @property
    def origins(self) -> list[str]:
        """Return the configured CORS origins as a list."""
        return [o.strip() for o in self.CORS_ALLOWED_ORIGINS.split(",") if o.strip()]

    class Config:
        env_file = ".env"
        extra    = "ignore"


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
