-- Migration 026 — Fix execution_mechanic CHECK constraint + add episode_steamroom_score
-- Date: 2026-05-19
-- Author: hotfix — two blocking bugs causing flow_events and flow_episodes tables to be empty
--
-- BUG 1 (flow_events) — code:23514 CHECK constraint violation on execution_mechanic
--   Migration 018 defined the constraint with the OLD order_side_classifier vocabulary:
--     DIRECTIONAL_LONG, DIRECTIONAL_SHORT, PASSIVE_BULLISH, PASSIVE_BEARISH,
--     AMBIGUOUS_LONG, AMBIGUOUS_SHORT
--
--   flow_store.py (post-refactor) now sends the NEW bid/ask + aggression vocabulary:
--     AGGRESSIVE_BUY, AGGRESSIVE_SELL, PASSIVE_BUY, PASSIVE_SELL, AMBIGUOUS_LONG
--
--   Every row with AGGRESSIVE_BUY / AGGRESSIVE_SELL / PASSIVE_BUY / PASSIVE_SELL
--   raised a CHECK violation → HTTP 400 → 3 retries → DISCARDED. flow_events empty.
--
-- BUG 2 (flow_episodes) — PGRST204: "Could not find the episode_steamroom_score column"
--   FIX-STEAMROOM-SCORE in flow_store.py calls _compute_episode_steamroom_score()
--   and writes episode_steamroom_score on every INSERT and PATCH. No migration was
--   ever written to add the column → PostgREST schema cache rejects every episode
--   INSERT → flow_episodes empty.
--
-- Idempotent: safe to re-run (IF NOT EXISTS + DROP CONSTRAINT IF EXISTS guards)

-- ──────────────────────────────────────────────────────────────────────────────
-- BUG 1 FIX: Replace execution_mechanic CHECK constraint
-- ──────────────────────────────────────────────────────────────────────────────

-- Step 1: Remap any existing rows that used the old vocabulary to AMBIGUOUS_LONG.
-- These are pre-refactor historical rows — the old values are no longer meaningful.
UPDATE public.flow_events
SET execution_mechanic = 'AMBIGUOUS_LONG'
WHERE execution_mechanic IN (
  'DIRECTIONAL_LONG',
  'DIRECTIONAL_SHORT',
  'PASSIVE_BULLISH',
  'PASSIVE_BEARISH',
  'AMBIGUOUS_SHORT'
);

-- Step 2: Drop the old CHECK constraint (name generated by Postgres from migration 018).
-- The constraint name pattern is: flow_events_execution_mechanic_check
ALTER TABLE public.flow_events
  DROP CONSTRAINT IF EXISTS flow_events_execution_mechanic_check;

-- Step 3: Add the new CHECK constraint matching what flow_store.py actually sends.
ALTER TABLE public.flow_events
  ADD CONSTRAINT flow_events_execution_mechanic_check
  CHECK (execution_mechanic IN (
    'AGGRESSIVE_BUY',
    'AGGRESSIVE_SELL',
    'PASSIVE_BUY',
    'PASSIVE_SELL',
    'AMBIGUOUS_LONG'
  ));

-- ──────────────────────────────────────────────────────────────────────────────
-- BUG 2 FIX: Add episode_steamroom_score to flow_episodes
-- ──────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.flow_episodes
  ADD COLUMN IF NOT EXISTS episode_steamroom_score INTEGER NOT NULL DEFAULT 0;

-- Optional index — supports leaderboard / top-conviction queries
CREATE INDEX IF NOT EXISTS idx_flow_episodes_steamroom_score
  ON public.flow_episodes (episode_steamroom_score DESC);

-- ──────────────────────────────────────────────────────────────────────────────
-- Verify (returns current constraint definition and column metadata)
-- ──────────────────────────────────────────────────────────────────────────────

-- Verify constraint was replaced
SELECT conname, pg_get_constraintdef(oid) AS definition
FROM pg_constraint
WHERE conrelid = 'public.flow_events'::regclass
  AND conname = 'flow_events_execution_mechanic_check';

-- Verify new column exists
SELECT column_name, data_type, column_default, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name   = 'flow_episodes'
  AND column_name  = 'episode_steamroom_score';
