-- SUPERSEDED by 20260507_ing010_gate_configs_and_audit.sql
-- This file is intentionally left as a tombstone to avoid git conflicts.
-- Do not apply this migration — seed data is included in ing010.
